baseURL      = "https://qisrepo.top/"
languageCode = "zh-CN"
title        = "QisRepo"
theme        = "hextra"

defaultContentLanguage = "zh-CN"

enableRobotsTXT = true
# Parse Git commit
enableGitInfo  = true
enableEmoji    = true
hasCJKLanguage = true

enableInlineShortcodes = true

[outputs]
  home    = ["html", "rss", "llms"]
  page    = ["html"]
  section = ["html", "rss"]

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight       = 1
  [languages.id]
    languageName = "Indonesian"
    languageCode = "id"
    weight       = 2
  [languages.zh-cn]
    languageName = "简体中文"
    languageCode = "zh-CN"
    weight       = 3

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "notes"
    name       = "Notes"
    pageRef    = "/notes"
    weight     = 1
  [[menu.main]]
    name   = "Search"
    weight = 10
    [menu.main.params]
      type = "search"
  
  [[menu.sidebar]]
    identifier = "more"
    name = "More"
    weight = 1
    [[menu.sidebar.params]]
      type = "separator"
  [[menu.sidebar]]
    name = "Tags"
    url = "/tags/"
    weight = 2

[params]
  dateFormat  = "2006-01-02"
  displayUpdatedDate = true
  externalLinkDecoration = true
  [params.navbar]
    [params.navbar.logo]
      path = "favicon.svg"
      dark = "favicon.svg"
  [params.footer]
    displayCopyright = true
  [params.editURL]
    enable = false
  [params.blog]
    [params.blog.list]
      displayTags = true
    [params.blog.article]
      displayPagination = true
  [params.comments]
    enable = true
    type   = "giscus"
    [params.comments.giscus]
      repo       = "cognden/website"
      repoId     = "R_kgDOOxy8JA"
      category   = "Announcements"
      categoryId = "DIC_kwDOOxy8JM4Cwn4w"

# 为每种语言设置特定的描述
[languages.en.params]
  description = "QisRepo is a personal tech blog focused on documenting learning processes, sharing programming experiences, and showcasing project outcomes. It includes my technical explorations, practical experiences, and personal growth journey."

[languages.id.params]
  description = "QisRepo adalah blog teknologi pribadi yang berfokus pada dokumentasi proses pembelajaran, berbagi pengalaman pemrograman, dan menampilkan hasil proyek. Ini mencakup eksplorasi teknis, pengalaman praktis, dan perjalanan pertumbuhan pribadi saya."

[languages.zh-cn.params]
  description = "QisRepo 是一个个人技术博客，专注于记录学习过程、分享编程经验和展示项目成果。这里包含了我的技术探索、实践经验和个人成长轨迹。"
